repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # latest stable pre-commit-hooks
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
        language_version: python3.14  # <- system python
        exclude: 'migrations/.*'
